// export { default as article } from "./article"
// export { default as callToAction } from "./callToAction"
export { default as customersBlock } from "./customersBlock"
export { default as leftImageBlock } from "./leftImageBlock"
export { default as rightImageBlock } from "./rightImageBlock"
export { default as gridBlock1 } from "./gridBlock1"
export { default as beigeBlock } from "./beigeBlock"
export { default as homeSlideBlock } from "./homeSlideBlock"
export { default as magentoBlock } from "./magentoBlock"
export { default as jamstackBlock } from "./jamstackBlock"
export { default as grid } from "./grid"